// ─────────────────────────────────────────────
// File: src/app/models/booking.model.ts (Final Update)
// ─────────────────────────────────────────────

export interface BookingRequest {
  passengerName: string;
  flightNumber: string;
  numOfAdults: number;   // Matches backend Java BookingDTO
  numOfChildren: number; // Matches backend Java BookingDTO
  seatNumber: string;
  ticketType: string;
  userEmail: string;
  totalFare: number;
}

export interface Booking {
  id?: number; // Changed to 'number' for MySQL database IDs
  passengerName: string;
  flightNumber: string;
  numOfAdults: number;   // Matches backend Java Booking entity
  numOfChildren: number; // Matches backend Java Booking entity
  seatNumber: string;
  ticketType: string;
  totalFare: number;
  passengerEmail?: string; // Added, optional as it might be set by backend
  passengerPhone?: string; // Added, optional as it might not be in DTO/entity
  bookingDate?: string; // Added, optional as it might be set by backend
  status?: string; // Added, optional as it might be set by backend
  ticketId?: string; // Added, optional, generated by backend
}
